### ISSUE TITLE
[Bug] 使用的网络代理不稳定，造成蜜柑计划RSS的XML下载失败

### ISSUE THREAD

**Issue by li-guohao** [ikaros-dev/ikaros#198]
### Search before asking

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### Ikaros Component

后端组件 (li-guohao/ikaros)

### What happened

使用的网络代理不稳定，造成蜜柑计划RSS的XML下载失败

### What you expected to happen

使用的网络代理不稳定，造成蜜柑计划RSS的XML下载失败，下面是部分日志：

<details><summary>ikaros.log</summary>

2022-12-17 07:30:00.003 DEBUG 1 --- [cheduled-Task-2] r.i.server.config.TaskManagerConfig      : current app init status=true
2022-12-17 07:30:00.004 DEBUG 1 --- [cheduled-Task-2] r.i.server.config.TaskManagerConfig      : current app ENABLE_AUTO_ANIME_SUB_TASK=true
2022-12-17 07:30:00.004 DEBUG 1 --- [cheduled-Task-2] r.i.server.config.TaskManagerConfig      : start exec task: pull anime subscribe and save metadata and download torrents
2022-12-17 07:30:00.004  INFO 1 --- [cheduled-Task-2] r.ikaros.server.service.TaskServiceImpl  : exec task: pullAnimeSubscribeAndSaveMetadataAndDownloadTorrents
2022-12-17 07:30:00.004  INFO 1 --- [cheduled-Task-2] r.ikaros.server.service.TaskServiceImpl  : start parse mikan my subscribe rss url from db
2022-12-17 07:30:00.237  INFO 1 --- [cheduled-Task-1] r.ikaros.server.service.TaskServiceImpl  : end task: searchDownloadProcessAndCreateFileHardLinksAndRelateEpisode
2022-12-17 07:30:00.238 DEBUG 1 --- [cheduled-Task-1] r.i.server.config.TaskManagerConfig      : current app ENABLE_GENERATE_MEDIA_DIR_TASK=true
2022-12-17 07:35:00.000 DEBUG 1 --- [cheduled-Task-1] r.i.server.config.TaskManagerConfig      : exec scheduled task: fiveMinuteOnceTask
2022-12-17 07:35:00.002 DEBUG 1 --- [cheduled-Task-1] r.i.server.config.TaskManagerConfig      : current app init status=true
2022-12-17 07:35:00.003 DEBUG 1 --- [cheduled-Task-1] r.i.server.config.TaskManagerConfig      : current app ENABLE_AUTO_ANIME_SUB_TASK=true
2022-12-17 07:35:00.003  INFO 1 --- [cheduled-Task-1] r.ikaros.server.service.TaskServiceImpl  : exec task: searchDownloadProcessAndCreateFileHardLinksAndRelateEpisode
2022-12-17 07:35:00.229  INFO 1 --- [cheduled-Task-1] r.ikaros.server.service.TaskServiceImpl  : end task: searchDownloadProcessAndCreateFileHardLinksAndRelateEpisode
2022-12-17 07:35:00.230 DEBUG 1 --- [cheduled-Task-1] r.i.server.config.TaskManagerConfig      : current app ENABLE_GENERATE_MEDIA_DIR_TASK=true
2022-12-17 07:40:00.000 DEBUG 1 --- [cheduled-Task-1] r.i.server.config.TaskManagerConfig      : exec scheduled task: fiveMinuteOnceTask
2022-12-17 07:40:00.003 DEBUG 1 --- [cheduled-Task-1] r.i.server.config.TaskManagerConfig      : current app init status=true
2022-12-17 07:40:00.003 DEBUG 1 --- [cheduled-Task-1] r.i.server.config.TaskManagerConfig      : current app ENABLE_AUTO_ANIME_SUB_TASK=true
2022-12-17 07:40:00.004  INFO 1 --- [cheduled-Task-1] r.ikaros.server.service.TaskServiceImpl  : exec task: searchDownloadProcessAndCreateFileHardLinksAndRelateEpisode
2022-12-17 07:40:00.241  INFO 1 --- [cheduled-Task-1] r.ikaros.server.service.TaskServiceImpl  : end task: searchDownloadProcessAndCreateFileHardLinksAndRelateEpisode
2022-12-17 07:40:00.242 DEBUG 1 --- [cheduled-Task-1] r.i.server.config.TaskManagerConfig      : current app ENABLE_GENERATE_MEDIA_DIR_TASK=true
2022-12-17 07:45:00.000 DEBUG 1 --- [cheduled-Task-3] r.i.server.config.TaskManagerConfig      : exec scheduled task: fiveMinuteOnceTask
2022-12-17 07:45:00.002 DEBUG 1 --- [cheduled-Task-3] r.i.server.config.TaskManagerConfig      : current app init status=true
2022-12-17 07:45:00.002 DEBUG 1 --- [cheduled-Task-3] r.i.server.config.TaskManagerConfig      : current app ENABLE_AUTO_ANIME_SUB_TASK=true
2022-12-17 07:45:00.003  INFO 1 --- [cheduled-Task-3] r.ikaros.server.service.TaskServiceImpl  : exec task: searchDownloadProcessAndCreateFileHardLinksAndRelateEpisode
2022-12-17 07:45:00.231  INFO 1 --- [cheduled-Task-3] r.ikaros.server.service.TaskServiceImpl  : end task: searchDownloadProcessAndCreateFileHardLinksAndRelateEpisode
2022-12-17 07:45:00.232 DEBUG 1 --- [cheduled-Task-3] r.i.server.config.TaskManagerConfig      : current app ENABLE_GENERATE_MEDIA_DIR_TASK=true
2022-12-17 07:46:08.050  WARN 1 --- [cheduled-Task-2] r.ikaros.server.service.RssServiceImpl   : fail write rss url xml file bytes to cache path: /tmp/ikaros/566faf72fb5e4d74bc6e12a46997615a.xml

javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1714) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1513) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580) ~[na:na]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187) ~[na:na]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142) ~[na:na]
        at run.ikaros.server.service.RssServiceImpl.downloadRssXmlFile(RssServiceImpl.java:130) ~[classes!/:na]
        at run.ikaros.server.service.RssServiceImpl.parseMikanMySubscribeRss(RssServiceImpl.java:64) ~[classes!/:na]
        at run.ikaros.server.service.RssServiceImpl$$FastClassBySpringCGLIB$$488c5813.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:166) ~[spring-retry-1.3.2.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at run.ikaros.server.service.RssServiceImpl$$EnhancerBySpringCGLIB$$32cc4cc6.parseMikanMySubscribeRss(<generated>) ~[classes!/:na]
        at run.ikaros.server.service.TaskServiceImpl.pullMikanRssAnimeSubscribeAndSaveMetadataAndDownloadTorrents(TaskServiceImpl.java:124) ~[classes!/:na]
        at run.ikaros.server.config.TaskManagerConfig.halfHourOnceTask(TaskManagerConfig.java:70) ~[classes!/:na]
        at jdk.internal.reflect.GeneratedMethodAccessor267.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.18.jar!/:5.3.18]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[na:na]
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505) ~[na:na]
        ... 32 common frames omitted

2022-12-17 07:46:08.052 ERROR 1 --- [cheduled-Task-2] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.NullPointerException: Cannot invoke "java.io.BufferedOutputStream.close()" because "bufferedOutputStream" is null
        at run.ikaros.server.service.RssServiceImpl.downloadRssXmlFile(RssServiceImpl.java:153) ~[classes!/:na]
        at run.ikaros.server.service.RssServiceImpl.parseMikanMySubscribeRss(RssServiceImpl.java:64) ~[classes!/:na]
        at run.ikaros.server.service.RssServiceImpl$$FastClassBySpringCGLIB$$488c5813.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:166) ~[spring-retry-1.3.2.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.18.jar!/:5.3.18]
        at run.ikaros.server.service.RssServiceImpl$$EnhancerBySpringCGLIB$$32cc4cc6.parseMikanMySubscribeRss(<generated>) ~[classes!/:na]
        at run.ikaros.server.service.TaskServiceImpl.pullMikanRssAnimeSubscribeAndSaveMetadataAndDownloadTorrents(TaskServiceImpl.java:124) ~[classes!/:na]
        at run.ikaros.server.config.TaskManagerConfig.halfHourOnceTask(TaskManagerConfig.java:70) ~[classes!/:na]
        at jdk.internal.reflect.GeneratedMethodAccessor267.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.18.jar!/:5.3.18]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.18.jar!/:5.3.18]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-12-17 07:50:00.000 DEBUG 1 --- [cheduled-Task-3] r.i.server.config.TaskManagerConfig      : exec scheduled task: fiveMinuteOnceTask
</details>

### How to reproduce

1. 保证网络无法正常访问蜜柑计划的RSS订阅
2. 等待Ikaros半小时一次的RSS订阅解析任务执行

### Are you willing to submit PR?

- [X] 是的我想要提交个PR!

**Comment by li-guohao** [comment]
这个对应的逻辑里面已经加了重试，无需做新的更改，网络问题可能严格来说不算Ikaros的BUG

**Comment by li-guohao** [comment]
这个问题有出现了：
- #222
