### ISSUE TITLE
[Bug] 文件搜索，当关键词出现特殊符号时无法搜索

### ISSUE THREAD

**Issue by li-guohao** [ikaros-dev/ikaros#224]
### Search before asking

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### Ikaros Component

后端组件 (li-guohao/ikaros)

### What happened

文件搜索，当关键词出现特殊符号时无法搜索，需要给URL参数添加编码

### What you expected to happen

文件搜索，当关键词出现特殊符号也能正常搜索

### How to reproduce

无

### Anything else

<details><summary>x.log</summary>
2022-12-22T15:15:56.380+08:00  INFO 1 --- [io-50000-exec-9] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in the request target [/api/file/list?page=1&size=8&keyword=[LoliHouse]+Shinmai+Renkinjutsushi+no+Tenpo+Keiei ]. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:494) ~[tomcat-embed-core-10.1.1.jar!/:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:272) ~[tomcat-embed-core-10.1.1.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-10.1.1.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) ~[tomcat-embed-core-10.1.1.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739) ~[tomcat-embed-core-10.1.1.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.1.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.1.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.1.jar!/:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.1.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
</details>

### Are you willing to submit PR?

- [ ] 是的我想要提交个PR!

**Comment by li-guohao** [comment]
解决办法是更新请求方式为POST
