### ISSUE TITLE
[Bug] 插入条目封面文件到文件表时，唯一键 folder_name_uk 重复

### ISSUE THREAD

**Issue by li-guohao** [ikaros-dev/ikaros#471]
### 提问前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 组件

插件 (plugin)

### 发生了什么

当我天降了天降之物的游戏条目后，再添加天降之物的漫画条目，由于游戏条目和漫画条目的名称一致，导致在保存封面文件到封面目录时，插入目录表报重复的唯一键 `folder_name_uk`，
```
Caused by: io.r2dbc.postgresql.ExceptionFactory$PostgresqlDataIntegrityViolationException: duplicate key value violates unique constraint "folder_name_uk"
```

解决方案就是`plugin-bgmtv` 在拉取到封面文件，保存文件目录关系时，默认将封面文件的名称，加上一个时间戳前缀，
比如原来条目封面文件名是 `天降之物.jpg` ，更新为 `1697160398-天降之物.jpg`

### 预期是怎样

预期当文件名称相同时，也能够正常的拉取

### 如何复现

不需

### 其它补充内容

```
023-10-13T09:15:35.238+08:00 DEBUG 7 --- [oundedElastic-3] r.i.p.b.repository.BgmTvRepositoryImpl   : Pull [https://api.bgm.tv/v0/subjects/359982] result is [{"date":"2010-04-02","platform":"全部游戏","images":{"small":"https://lain.bgm.tv/r/200/pic/cover/l/12/78/359982_khm7m.jpg","grid":"https://lain.bgm.tv/r/100/pic/cover/l/12/78/359982_khm7m.jpg","large":"https://lain.bgm.tv/pic/cover/l/12/78/359982_khm7m.jpg","medium":"https://lain.bgm.tv/r/800/pic/cover/l/12/78/359982_khm7m.jpg","common":"https://lain.bgm.tv/r/400/pic/cover/l/12/78/359982_khm7m.jpg"},"summary":"本作为一款以目前正在角川书店发行的《月刊少年Ace》上连载中，并于2009年10月推出电视动画版的人气作品《天降之物》为题材改编而成的一款养成游戏。游戏中描述座右铭为“和平第一”的普通高中生樱井智树在跟从天空降下的未确认生物───伊卡洛斯相遇之后所引发的种种有趣故事。至于在游戏版里，则将以游戏原创故事为主题，描述由于伊卡洛斯失去记忆，因此身为主角的樱井智树，必须使用魔法卡片来让伊卡洛斯再度学会各式各样的“关键词”意义。\r\n以动漫《天降之物》为题材的PSP平台育成类游戏《天降之物：心跳的暑假》将会在2010年3月25日发售，相信其激萌的美少女角色会吸引到不少玩家。\r\n在《天降之物：心跳的暑假》中，剧情将为完全原创。玩家扮演男主角樱井智树，为了失去记忆的伊卡洛斯，使用各种魔法卡片提示出关键词唤醒伊卡洛斯的过去。\r\n游戏中提供了各种不同的卡片，如可以培养伊卡洛斯感情的“交流卡片（コミュニケ-ションカ-ド）”、可以实现换装的“Cosplay卡片（コスプレカ-ド）”和可以发生不同剧情的“事件卡片（イベントカ-ド）。根据使用卡片的不同，对剧情分支也会有不同的影响。","name":"そらのおとしもの:ドキドキサマーバケーション","name_cn":"天降之物:心跳的暑假","tags":[{"name":"后宫","count":2}],"infobox":[{"key":"中文名","value":"天降之物:心跳的暑假"},{"key":"别名","value":[{"v":"天降之物：动心的暑假"},{"v":"Sora no Otoshimono: Doki Doki Sunmmer Vacation"}]},{"key":"平台","value":[{"v":"psp"}]},{"key":"游戏类型","value":"avg冒险"},{"key":"游玩人数","value":"1"},{"key":"发行日期","value":"2010-04-02"},{"key":"地区","value":"日本"},{"key":"开发","value":"Kadokawa Shoten"},{"key":"制作发行","value":"Kadokawa Shoten"}],"rating":{"rank":0,"total":4,"count":{"1":0,"2":0,"3":0,"4":1,"5":0,"6":0,"7":1,"8":2,"9":0,"10":0},"score":6.8},"total_episodes":0,"collection":{"on_hold":0,"dropped":1,"wish":6,"collect":6,"doing":0},"id":359982,"eps":0,"volumes":0,"locked":false,"nsfw":false,"type":4}
].
2023-10-13T09:15:35.243+08:00 DEBUG 7 --- [oundedElastic-3] r.i.p.b.repository.BgmTvRepositoryImpl   : Pull [https://api.bgm.tv/v0/subjects/359982] result infobox is [[{key=中文名, value=天降之物:心跳的暑假}, {key=别名, value=[{v=天降之物：动心的暑假}, {v=Sora no Otoshimono: Doki Doki Sunmmer Vacation}]}, {key=平台, value=[{v=psp}]}, {key=游戏类型, value=avg冒险}, {key=游玩人数, value=1}, {key=发行日期, value=2010-04-02}, {key=地区, value=日本}, {key=开发, value=Kadokawa Shoten}, {key=制作发行, value=Kadokawa Shoten}]].
2023-10-13T09:15:35.271+08:00  INFO 7 --- [oundedElastic-3] r.i.p.bgmtv.BgmTvSubjectSynchronizer     : Pull subject:[そらのおとしもの:ドキドキサマーバケーション] by platform:[BGM_TV] and id:[359982]
2023-10-13T09:15:35.666+08:00  INFO 7 --- [oundedElastic-3] r.i.p.bgmtv.BgmTvSubjectSynchronizer     : Pull episode count:[0] by platform:[BGM_TV] and id:[359982]
2023-10-13T09:16:31.752+08:00 DEBUG 7 --- [oundedElastic-3] r.i.p.b.repository.BgmTvRepositoryImpl   : Pull [https://api.bgm.tv/v0/subjects/9518] result is [{"date":null,"platform":"漫画","images":{"small":"https://lain.bgm.tv/r/200/pic/cover/l/18/fe/9518_8T199.jpg","grid":"https://lain.bgm.tv/r/100/pic/cover/l/18/fe/9518_8T199.jpg","large":"https://lain.bgm.tv/pic/cover/l/18/fe/9518_8T199.jpg","medium":"https://lain.bgm.tv/r/800/pic/cover/l/18/fe/9518_8T199.jpg","common":"https://lain.bgm.tv/r/400/pic/cover/l/18/fe/9518_8T199.jpg"},"summary":"　　這是一段少年與從天空墜落之不明生物的——歡樂愛情物語……\r\n\r\n　　我的名字是櫻井智樹，座右銘為「和平至上」。平凡不就是最好的嗎？若要說唯一不尋常的地方…就是我常作到的夢，會夢到一個連長相也回想不起來的女孩。我因為那終究只是場夢而沒有放在心上，但是……\r\n\r\n　　直到那天，天使從天而降————","name":"そらのおとしもの","name_cn":"天降之物","tags":[{"name":"漫画","count":141},{"name":"水無月すう","count":134},{"name":"后宫","count":128},{"name":"搞笑","count":94},{"name":"天降之物","count":69},{"name":"杀必死","count":40},{"name":"卖肉","count":38},{"name":"科幻","count":32},{"name":"肉","count":27},{"name":"天使","count":20},{"name":"神展开","count":19},{"name":"变态","count":18},{"name":"2007","count":16},{"name":"そらのおとしもの","count":10},{"name":"天降妹子","count":9},{"name":"已完结","count":7},{"name":"节操","count":6},{"name":"漫画系列","count":6},{"name":"校园","count":6},{"name":"恋爱","count":5},{"name":"系列","count":3},{"name":"福利","count":3},{"name":"角川書店","count":3},{"name":"燃系","count":3},{"name":"水无月嵩","count":2},{"name":"月刊","count":2},{"name":"完结","count":2},{"name":"治愈","count":2},{"name":"少年漫画","count":2},{"name":"恋爱漫画","count":1}],"infobox":[{"key":"中文名","value":"天降之物"},{"key":"别名","value":[{"v":"sora no otoshimono"}]},{"key":"出版社","value":"角川書店、台灣角川"},{"key":"连载杂志","value":"月刊少年エース、エースアサルト(番外篇)"},{"key":"册数","value":"20"},{"key":"话数","value":"77+20EX(番外篇)"},{"key":"其他","value":"《月刊少年Ace》2014年4、5月号刊载完结番外篇"},{"key":"作者","value":"水無月すう"},{"key":"开始","value":"2007-03-26(2007年5月号)"},{"key":"结束","value":"2014-01-25(2014年3月号)"}],"rating":{"rank":805,"total":489,"count":{"1":1,"2":0,"3":1,"4":3,"5":6,"6":31,"7":120,"8":191,"9":87,"10":49},"score":7.9},"total_episodes":0,"collection":{"on_hold":36,"dropped":15,"wish":170,"collect":639,"doing":65},"id":9518,"eps":77,"volumes":20,"locked":false,"nsfw":false,"type":1}
].
2023-10-13T09:16:31.755+08:00 DEBUG 7 --- [oundedElastic-3] r.i.p.b.repository.BgmTvRepositoryImpl   : Pull [https://api.bgm.tv/v0/subjects/9518] result infobox is [[{key=中文名, value=天降之物}, {key=别名, value=[{v=sora no otoshimono}]}, {key=出版社, value=角川書店、台灣角川}, {key=连载杂志, value=月刊少年エース、エースアサルト(番外篇)}, {key=册数, value=20}, {key=话数, value=77+20EX(番外篇)}, {key=其他, value=《月刊少年Ace》2014年4、5月号刊载完结番外篇}, {key=作者, value=水無月すう}, {key=开始, value=2007-03-26(2007年5月号)}, {key=结束, value=2014-01-25(2014年3月号)}]].
2023-10-13T09:16:31.760+08:00  INFO 7 --- [oundedElastic-3] r.i.p.bgmtv.BgmTvSubjectSynchronizer     : Pull subject:[そらのおとしもの] by platform:[BGM_TV] and id:[9518]
2023-10-13T09:16:32.045+08:00  INFO 7 --- [oundedElastic-3] r.i.p.bgmtv.BgmTvSubjectSynchronizer     : Pull episode count:[0] by platform:[BGM_TV] and id:[9518]
2023-10-13T09:16:34.142+08:00 ERROR 7 --- [tor-tcp-epoll-1] s.c.s.s.i.SubjectSyncPlatformServiceImpl : Operate has exception for platform-id: BGM_TV-9518, plugin exception msg: execute; SQL [UPDATE file SET folder_id = $1, url = $2, fs_path = $3, name = $4, md5 = $5, aes_key = $6, size = $7, type = $8, can_read = $9, update_time = $10 WHERE file.id = $11]; duplicate key value violates unique constraint "folder_name_uk"

org.springframework.dao.DuplicateKeyException: execute; SQL [UPDATE file SET folder_id = $1, url = $2, fs_path = $3, name = $4, md5 = $5, aes_key = $6, size = $7, type = $8, can_read = $9, update_time = $10 WHERE file.id = $11]; duplicate key value violates unique constraint "folder_name_uk"
        at org.springframework.r2dbc.connection.ConnectionFactoryUtils.convertR2dbcException(ConnectionFactoryUtils.java:235) ~[spring-r2dbc-6.0.3.jar:6.0.3]
        at org.springframework.r2dbc.core.DefaultDatabaseClient.lambda$inConnection$4(DefaultDatabaseClient.java:128) ~[spring-r2dbc-6.0.3.jar:6.0.3]
        at reactor.core.publisher.Mono.lambda$onErrorMap$27(Mono.java:3749) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.Mono.lambda$onErrorResume$29(Mono.java:3839) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoUsingWhen$MonoUsingWhenSubscriber.deferredError(MonoUsingWhen.java:277) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxUsingWhen$RollbackInner.onComplete(FluxUsingWhen.java:475) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:531) ~[reactor-pool-1.0.0.jar:1.0.0]
        at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:761) ~[reactor-pool-1.0.0.jar:1.0.0]
        at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:873) ~[reactor-pool-1.0.0.jar:1.0.0]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onComplete(FluxHandleFuseable.java:238) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoSupplier$MonoSupplierSubscription.request(MonoSupplier.java:148) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.request(FluxHandleFuseable.java:259) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onSubscribe(MonoIgnoreElements.java:72) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onSubscribe(FluxHandleFuseable.java:163) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:48) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:84) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxFilter$FilterSubscriber.onError(FluxFilter.java:157) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxFilter$FilterConditionalSubscriber.onError(FluxFilter.java:291) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.Operators.error(Operators.java:198) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoError.subscribe(MonoError.java:53) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4444) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onError(FluxUsingWhen.java:364) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoStreamCollector$StreamCollectorSubscriber.onError(MonoStreamCollector.java:149) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:134) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:842) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxFlatMap$FlatMapMain.innerError(FluxFlatMap.java:863) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxFlatMap$FlatMapInner.onError(FluxFlatMap.java:990) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onError(FluxHandleFuseable.java:228) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onError(MonoCollectList.java:108) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onError(FluxHandle.java:212) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onError(MonoFlatMapMany.java:255) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:200) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.5.1.jar:3.5.1]
        at io.r2dbc.postgresql.util.FluxDiscardOnCancel$FluxDiscardOnCancelSubscriber.onNext(FluxDiscardOnCancel.java:91) ~[r2dbc-postgresql-1.0.0.RELEASE.jar:1.0.0.RELEASE]
        at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:128) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:814) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:739) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:161) ~[reactor-core-3.5.1.jar:3.5.1]
        at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:687) ~[r2dbc-postgresql-1.0.0.RELEASE.jar:1.0.0.RELEASE]
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:939) ~[r2dbc-postgresql-1.0.0.RELEASE.jar:1.0.0.RELEASE]
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:813) ~[r2dbc-postgresql-1.0.0.RELEASE.jar:1.0.0.RELEASE]
        at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:719) ~[r2dbc-postgresql-1.0.0.RELEASE.jar:1.0.0.RELEASE]
        at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:128) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:224) ~[reactor-core-3.5.1.jar:3.5.1]
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:292) ~[reactor-netty-core-1.1.1.jar:1.1.1]
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:401) ~[reactor-netty-core-1.1.1.jar:1.1.1]
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:411) ~[reactor-netty-core-1.1.1.jar:1.1.1]
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113) ~[reactor-netty-core-1.1.1.jar:1.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: io.r2dbc.postgresql.ExceptionFactory$PostgresqlDataIntegrityViolationException: duplicate key value violates unique constraint "folder_name_uk"
        at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:102) ~[r2dbc-postgresql-1.0.0.RELEASE.jar:1.0.0.RELEASE]
        at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:65) ~[r2dbc-postgresql-1.0.0.RELEASE.jar:1.0.0.RELEASE]
        at io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:132) ~[r2dbc-postgresql-1.0.0.RELEASE.jar:1.0.0.RELEASE]
        at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178) ~[reactor-core-3.5.1.jar:3.5.1]
        ... 43 common frames omitted
```

### 您将要去提交PR吗？

- [X] 是的我想要提交个PR!

**Comment by li-guohao** [comment]
也可以这种命名 `[Anime] xxxx.jpg`

**Comment by li-guohao** [comment]
fix by commit: https://github.com/ikaros-dev/plugin-bgmtv/commit/653a13114587a43523a62e38a2c3bc85357d07e5
