### ISSUE TITLE
[Bug] 条目关系无法正常移除

### ISSUE THREAD

**Issue by jerryyang-git** [ikaros-dev/ikaros#608]
### 提问前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 组件

服务端 (server)

### 运行环境

部署方式：docker
版本：0.13.0

### 报错相关的日志

```shell
{
  "exception": "java.lang.NumberFormatException",
  "message": "For input string: \"relation\""
}
```

### 发生了什么

条目与条目绑定关系后无法删除
![image](https://github.com/ikaros-dev/ikaros/assets/60727068/ffd38aa1-d567-4e36-bfd0-c1a0a3d79a2b)

### 预期是怎样

正常删除条目关联，且如果删除条目之后，该条目连带的关系也一并删除

### 如何复现

使用bgm插件添加两个条目，相互绑定关系，然后删除关系

### 您将要去提交PR吗？

- [ ] 是的我想要提交个PR!

**Comment by chivehao** [comment]
条目绑定只需要绑定一边就行了，另一边会自动绑定的，不需要两边都去操作下。
比如
CLANNAD 和 CLANNAD AF

只需要下面的操作二选一：

- 在CLANNAD的条目里添加CLANNAD AF为后传
- 在CLANNAD AF的条目里添加CLANNAD为前传

**Comment by chivehao** [comment]
日志请给详细点，起码要有异常日志堆栈

**Comment by jerryyang-git** [comment]
> 条目绑定只需要绑定一边就行了，另一边会自动绑定的

我只绑定了一边，是删除操作的时候报错了

> 日志请给详细点，起码要有异常日志堆栈

好的，下面是我删除关系后的 Logs

```
2024-07-09 23:21:16     at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onSubscribe(FluxPeekFuseable.java:471)
2024-07-09 23:21:16     at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152)
2024-07-09 23:21:16     at reactor.core.publisher.Operators$BaseFluxToMonoOperator.onSubscribe(Operators.java:2025)
2024-07-09 23:21:16     at reactor.core.publisher.MonoNext$NextSubscriber.onSubscribe(MonoNext.java:70)
2024-07-09 23:21:16     at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onSubscribe(FluxConcatMapNoPrefetch.java:164)
2024-07-09 23:21:16     at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
2024-07-09 23:21:16     at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
2024-07-09 23:21:16     at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
2024-07-09 23:21:16     at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
2024-07-09 23:21:16     at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
2024-07-09 23:21:16     at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
2024-07-09 23:21:16     at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
2024-07-09 23:21:16     at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
2024-07-09 23:21:16     at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
2024-07-09 23:21:16     at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
2024-07-09 23:21:16     at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
2024-07-09 23:21:16     at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166)
2024-07-09 23:21:16     at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940)
2024-07-09 23:21:16     at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85)
2024-07-09 23:21:16     at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2547)
2024-07-09 23:21:16     at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341)
2024-07-09 23:21:16     at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2215)
2024-07-09 23:21:16     at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
2024-07-09 23:21:16     at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
2024-07-09 23:21:16     at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82)
2024-07-09 23:21:16     at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
2024-07-09 23:21:16     at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166)
2024-07-09 23:21:16     at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846)
2024-07-09 23:21:16     at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608)
2024-07-09 23:21:16     at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588)
2024-07-09 23:21:16     at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465)
2024-07-09 23:21:16     at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277)
2024-07-09 23:21:16     at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:357)
2024-07-09 23:21:16     at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:294)
2024-07-09 23:21:16     at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144)
2024-07-09 23:21:16     at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
2024-07-09 23:21:16     at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178)
2024-07-09 23:21:16     at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
2024-07-09 23:21:16     at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83)
2024-07-09 23:21:16     at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
2024-07-09 23:21:16     at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
2024-07-09 23:21:16     at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
2024-07-09 23:21:16     at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071)
2024-07-09 23:21:16     at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:134)
2024-07-09 23:21:16     at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
2024-07-09 23:21:16     at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
2024-07-09 23:21:16     at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166)
2024-07-09 23:21:16     at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:275)
2024-07-09 23:21:16     at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1840)
2024-07-09 23:21:16     at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337)
2024-07-09 23:21:16     at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354)
2024-07-09 23:21:16     at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
2024-07-09 23:21:16     at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
2024-07-09 23:21:16     at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
2024-07-09 23:21:16     at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
2024-07-09 23:21:16     at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
2024-07-09 23:21:16     at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
2024-07-09 23:21:16     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2024-07-09 23:21:16     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
2024-07-09 23:21:16     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024-07-09 23:21:16     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024-07-09 23:21:16     at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by chivehao** [comment]
你是绑定了自己嘛？
比如CLANNAD绑定自己，关系类型是动漫

**Comment by chivehao** [comment]
不清楚咋复现

**Comment by chivehao** [comment]
> 我删除关系后的 Logs
额，这个日志其实没啥有效信息

**Comment by chivehao** [comment]
> 预期是怎样
正常删除条目关联，且如果删除条目之后，该条目连带的关系也一并删除

请问这里时指删除条目关联关系，还是指删除条目

> 如何复现
使用bgm插件添加两个条目，相互绑定关系，然后删除关系

复现步骤能否详细点，这步骤我不知道咋复现

**Comment by jerryyang-git** [comment]
> 复现步骤能否详细点，这步骤我不知道咋复现

这个是我的操作步骤  [视频（临时）](https://azusa-mikan.frp.wo25.net:32000/%E5%BD%95%E5%88%B6_2024_07_09_23_43_12_103.mp4)

**Comment by chivehao** [comment]
> > 复现步骤能否详细点，这步骤我不知道咋复现
> 
> 这个是我的操作步骤
> 
> https://azusa-mikan.frp.wo25.net:32000/%E5%BD%95%E5%88%B6_2024_07_09_23_43_12_103.mp4

好的谢谢我看下

**Comment by chivehao** [comment]
找到问题了，应该很快可以解决了
