### ISSUE TITLE
[Bug]  迁移到POSTGRESQL数据库后 bad SQL grammar [SELECT subject.* FROM subject]错误

### ISSUE THREAD

**Issue by gsxgmpkt9020** [ikaros-dev/ikaros#742]
### 提问前查询

- [X] 我已经在 [issues](https://github.com/ikaros-dev/ikaros/issues?q=is%3Aissue) 列表 里查询过，并且没找到类似的问题。

### 组件

服务端 (server)

### 运行环境

WIN 10
POSTGRESQL 17

JAVA20

 java 20.0.1 2023-04-18
Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

### 报错相关的日志

```shell
2024-12-03 22:41:21 [reactor-tcp-nio-1] ERROR reactor.core.publisher.Operators - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [SELECT subject.* FROM subject]
Caused by: org.springframework.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [SELECT subject.* FROM subject]
        at org.springframework.r2dbc.connection.ConnectionFactoryUtils.convertR2dbcException(ConnectionFactoryUtils.java:243)
        at org.springframework.r2dbc.core.DefaultDatabaseClient.lambda$inConnectionMany$8(DefaultDatabaseClient.java:150)
        at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:7123)
        at reactor.core.publisher.Flux.lambda$onErrorResume$29(Flux.java:7176)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.deferredError(FluxUsingWhen.java:398)
        at reactor.core.publisher.FluxUsingWhen$RollbackInner.onComplete(FluxUsingWhen.java:475)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209)
        at reactor.pool.SimpleDequePool.maybeRecycleAndDrain(SimpleDequePool.java:531)
        at reactor.pool.SimpleDequePool$QueuePoolRecyclerInner.onComplete(SimpleDequePool.java:761)
        at reactor.core.publisher.Operators.complete(Operators.java:137)
        at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
        at reactor.pool.SimpleDequePool$QueuePoolRecyclerMono.subscribe(SimpleDequePool.java:873)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
        at reactor.core.publisher.Operators.complete(Operators.java:137)
        at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4444)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
        at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
```

### 发生了什么

因为担心H2数据库的可靠性想要换数据库载体。把之前的ikaros配置文件清空以后，连接到POSTGRESQL出现报错

无法运行启动；浏览器显示

{"exception":"org.springframework.r2dbc.BadSqlGrammarException","message":"executeMany; bad SQL grammar [SELECT custom.* FROM custom WHERE (custom.c_group = $1) AND (custom.version = $2) AND (custom.kind = $3) AND (custom.name = $4) LIMIT 2]"}

POSTGRESQL数据库是提前自建空的，不知道有没有什么要求硬性要求

### 预期是怎样

浏览器显示显示管理界面

### 如何复现

FAST JAR 带参数启动

java -jar "C:\Games\ikaros\ikaros-server.jar" --spring.profiles.active=win --spring.sql.init.platform=postgresql --spring.r2dbc.url=r2dbc:pool:postgresql://127.0.0.1:5432/ikaros --spring.r2dbc.username=ikaros --spring.r2dbc.password='mmfXXXXXX9B2'

### 其它补充内容

[error.log](https://github.com/user-attachments/files/17994924/error.log)
[ikaros.log](https://github.com/user-attachments/files/17994925/ikaros.log)

**Comment by chivehao** [comment]
> FAST JAR 带参数启动
>
> java -jar "C:\Games\ikaros\ikaros-server.jar" --spring.profiles.active=win --spring.sql.init.platform=postgresql --spring.r2dbc.url=r2dbc:pool:postgresql://127.0.0.1:5432/ikaros --spring.r2dbc.username=ikaros --spring.r2dbc.password='mmfXXXXXX9B2'

可能是参数问题，

- `--spring.profiles.active=win` 修改为：`--spring.profiles.active=win,postgresql`
- 还需要加上flyway的连接配置：`--spring.flyway.url=jdbc:postgresql://localhost:5432/postgres` `--spring.flyway.user=xxx` `--spring.flyway.password=xxx`

**Comment by chivehao** [comment]
我在文档上没有写清楚需要配置flyway数据库配置，后面有空我更新下文档。

**Comment by chivehao** [comment]
> > 我在文档上没有写清楚需要配置flyway数据库配置，后面有空我更新下文档。
> > https://docs.ikaros.run/docs/getting-started/install/fast-jar
> 
> 您好，请教一下，为什么dockercompose的配置这边是数据库ikaros_database/ikaros，用户名ikaros
> 
> ```
>       - --spring.r2dbc.url=r2dbc:pool:postgresql://ikaros_database/ikaros
>       - --spring.r2dbc.username=ikaros
> ```
> 
> 而fast-jar这边是自定义的？
> 
> spring.r2dbc.username 数据库用户名 spring.r2dbc.password 数据库密码
> 
> 是因为容器提前准备好了更多数据让免去我们自建，还是说容器会先自动创建H2数据库ikaros然后通过flayway无缝迁移到P-SQL？

需要结合上下文，
`r2dbc:pool:postgresql://ikaros_database/ikaros` 里的 `ikaros_database` 是 `docker-compose.yaml` 里配置的容器名称，相当于 `localhost:5432`，数据库名称就是 `ikaros`

我截取的是`docker-compose.yaml`文件里的部分内容，里面已经定义了数据库容器：

```
    # ikaros database
    ikaros_database:
        image: postgres:latest
        container_name: ikaros_database
        restart: on-failure:3
        networks:
          ikaros_networks:
        volumes:
          - ./database:/var/lib/postgresql/data
        healthcheck:
          test: [ "CMD", "pg_isready" ]
          interval: 10s
          timeout: 5s
          retries: 5
        environment:
          - POSTGRES_DB=ikaros
          - POSTGRES_USER=ikaros
          - POSTGRES_PASSWORD=openpostgresql
```

完整文件请看：https://docs.ikaros.run/docs/getting-started/install/docker-compose 的场景`创建 Ikaros + PostgreSQL 的实例`

**Comment by chivehao** [comment]
r2dbc和flyway的jdbc，这两边要连同一个数据库哈，数据库地址，端口、啥的配置都需要相同
